### ISSUE TITLE
Missing values

### ISSUE THREAD

**Issue by webfrank** [kadalu/gluster-metrics-exporter#23]
Hi, I've just installed the exporter but I have some missing values:

- brick_cpu_percentage
- brick_memory_percentage
- brick_uptime_seconds

and these tow are always zero:
- glusterd_cpu_percentage
- glusterd_memory_percentage

Is this expected or I need to configure something?

**Comment by aravindavk** [comment]
I will look into the issue. Please confirm that Metrics exporter is installed and started in all the Storage nodes.

**Comment by webfrank** [comment]
Hi, yes, I have it on three nodes

**Comment by aravindavk** [comment]
Try the latest release(0.2.1). Fixed an parse issue in glustercli library(https://github.com/aravindavk/glustercli-crystal/pull/1)

**Comment by aravindavk** [comment]
Tested in my setup.

```console
$ curl -s http://0.0.0.0:9713/metrics | grep "brick_cpu\|brick_memory"
# HELP brick_cpu_percentage Brick CPU Percentage
# TYPE brick_cpu_percentage gauge
brick_cpu_percentage{cluster="DEV", volume_type="Distribute", volume_state="Started", volume_name="vol1", subvol_index="0", hostname="gserver1", path="/exports/vol1/s1"} 45.0
# HELP brick_memory_percentage Brick Memory Percentage
# TYPE brick_memory_percentage gauge
brick_memory_percentage{cluster="DEV", volume_type="Distribute", volume_state="Started", volume_name="vol1", subvol_index="0", hostname="gserver1", path="/exports/vol1/s1"} 2.7
```

**Comment by webfrank** [comment]
Hi, just upgraded, now I have the values but are zero all the time:

```
# HELP brick_cpu_percentage Brick CPU Percentage
# TYPE brick_cpu_percentage gauge
brick_cpu_percentage{cluster="ovh", volume_type="Distributed-Replicate", volume_state="Started", volume_name="glfs", subvol_index="0", hostname="ovh4", path="/mnt/gfs/data1/brick1"} 0.0
brick_cpu_percentage{cluster="ovh", volume_type="Distributed-Replicate", volume_state="Started", volume_name="glfs", subvol_index="0", hostname="ovh5", path="/mnt/gfs/data2/brick2"} 0.0
brick_cpu_percentage{cluster="ovh", volume_type="Distributed-Replicate", volume_state="Started", volume_name="glfs", subvol_index="1", hostname="ovh4", path="/mnt/gfs/data2/brick2"} 0.0
brick_cpu_percentage{cluster="ovh", volume_type="Distributed-Replicate", volume_state="Started", volume_name="glfs", subvol_index="1", hostname="ovh5", path="/mnt/gfs/data1/brick1"} 0.0
.......
# HELP brick_memory_percentage Brick Memory Percentage
# TYPE brick_memory_percentage gauge
brick_memory_percentage{cluster="ovh", volume_type="Distributed-Replicate", volume_state="Started", volume_name="glfs", subvol_index="0", hostname="ovh4", path="/mnt/gfs/data1/brick1"} 0.0
brick_memory_percentage{cluster="ovh", volume_type="Distributed-Replicate", volume_state="Started", volume_name="glfs", subvol_index="0", hostname="ovh5", path="/mnt/gfs/data2/brick2"} 0.0
brick_memory_percentage{cluster="ovh", volume_type="Distributed-Replicate", volume_state="Started", volume_name="glfs", subvol_index="1", hostname="ovh4", path="/mnt/gfs/data2/brick2"} 0.0
brick_memory_percentage{cluster="ovh", volume_type="Distributed-Replicate", volume_state="Started", volume_name="glfs", subvol_index="1", hostname="ovh5", path="/mnt/gfs/data1/brick1"} 0.0
.......
# HELP glusterd_cpu_percentage Glusterd CPU Percentage
# TYPE glusterd_cpu_percentage gauge
glusterd_cpu_percentage{cluster="ovh", hostname="ovh4"} 0.0
glusterd_cpu_percentage{cluster="ovh", hostname="ovh5"} 0.0
glusterd_cpu_percentage{cluster="ovh", hostname="ovh3.bizmate.it"} 0.0
# HELP glusterd_memory_percentage Glusterd Memory Percentage
# TYPE glusterd_memory_percentage gauge
glusterd_memory_percentage{cluster="ovh", hostname="ovh4"} 0.0
glusterd_memory_percentage{cluster="ovh", hostname="ovh5"} 0.0
glusterd_memory_percentage{cluster="ovh", hostname="ovh3.bizmate.it"} 0.0
```

Do I need to enable something on gluster to enable these metrics?

**Comment by aravindavk** [comment]
To collect CPU and Memory metrics it is running `top -b -n 2 -d 0.2 -p <Brick_PID>` in the storage nodes

**Comment by aravindavk** [comment]
Found the issue. The dependencies are not upgraded in the automated build job. Looking into the issue. Will make one more release with the fix.

**Comment by aravindavk** [comment]
Please check now. Sorry for the last faulty build.

**Comment by webfrank** [comment]
Hi, just upgraded but now I have this error:

2022-01-11 08:15:00 UTC 500 GET /_api/local-metrics 370.34ms
Exception: Invalid Float64: 0,0 (ArgumentError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???

2022-01-11 08:15:03 UTC 500 GET /_api/local-metrics 370.94ms
2022-01-11 08:15:03 UTC 200 GET /metrics 1302.35ms

**Comment by aravindavk** [comment]
That is strange. I will try to reproduce the issue locally.

I made one more release with couple of enhancements. Please check.

https://github.com/kadalu/gluster-metrics-exporter/releases/tag/0.3.0

In this release, I added basic tests and test output looks positive(https://github.com/kadalu/gluster-metrics-exporter/runs/4777488489?check_suite_focus=true). I will add more tests soon.

**Comment by aravindavk** [comment]
> It seems a parsing error due to different locales (0,0 instead of 0.0)

Ok. Let me check. Please share the output of `top -b -n 2 -d 0.2 -p <Brick_PID>` so that I will try to reproduce the issue if the top command is returning value in that format.

**Comment by aravindavk** [comment]
In the latest release, many things simplified. For example, removed the Cluster name label since Prometheus `job` label can be used as Cluster name. Local hostname is automatically picked by running the `hostname` command. Added systemd service file and installation steps reduced to one step. Refer README for more details about the usage. https://github.com/kadalu/gluster-metrics-exporter#readme

**Comment by webfrank** [comment]
> 

Sorry for late reply, this is the output of top:

```
top - 16:30:03 up 371 days,  5:14,  2 users,  load average: 3,16, 3,02, 2,99
Tasks:   1 total,   0 running,   1 sleeping,   0 stopped,   0 zombie
%Cpu(s): 17,4 us,  0,8 sy,  0,0 ni, 80,9 id,  0,0 wa,  0,0 hi,  0,8 si,  0,0 st
MiB Mem : 257665,4 total,   1681,9 free,  97038,8 used, 158944,7 buff/cache
MiB Swap:      0,0 total,      0,0 free,      0,0 used. 156065,6 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 2189 root      20   0 2235024  48144   3884 S   6,7   0,0  11489:46 glusterfsd

top - 16:30:03 up 371 days,  5:14,  2 users,  load average: 3,16, 3,02, 2,99
Tasks:   1 total,   0 running,   1 sleeping,   0 stopped,   0 zombie
%Cpu(s): 18,3 us,  1,9 sy,  0,0 ni, 78,8 id,  0,0 wa,  0,0 hi,  1,0 si,  0,0 st
MiB Mem : 257665,4 total,   1681,9 free,  97038,8 used, 158944,7 buff/cache
MiB Swap:      0,0 total,      0,0 free,      0,0 used. 156065,6 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 2189 root      20   0 2235024  48144   3884 S   0,0   0,0  11489:46 glusterfsd
```

**Comment by webfrank** [comment]
Hi, it seems it is working now.

To have CPU/Memory percentage I'm using this query

`avg(brick_memory_percentage) by (hostname)`

Is it the correct one?

**Comment by aravindavk** [comment]
Thanks for the example output. Fixed the issue in glustercli library https://github.com/aravindavk/glustercli-crystal/pull/4

I will make new release once this PR merges https://github.com/kadalu/gluster-metrics-exporter/pull/27
