### ISSUE TITLE
Metric prefix name (possible breaking)

### ISSUE THREAD

**Issue by frenkye** [kadalu/gluster-metrics-exporter#35]
Would it be possible to implement metrics prefixes to unite the namespace of all metrics from the exporter?

I know we could set up relabeling at the Prometheus level, but I don't think that is the correct way. When there are precedents from other service exporters.

This is better for workflow with metrics too, because no one likes to remember all types of metrics exporter returns, but if there is anything to unite them it is easier to search within them.

I see 2 options:
1. breaking change a set up "glusterfs_" prefix or something like that.
2. Introduce a new flag to the exporter which will prefix all metrics empty string by default and possibly in the future change permanently.

**Comment by aravindavk** [comment]
Ack. I will add prefix to the exported metrics.
