### ISSUE TITLE
Arithmetic overflow with all modules on

### ISSUE THREAD

**Issue by JanSoderback** [kadalu/gluster-metrics-exporter#40]
With release 0.5.0 (and earlier release 0.4.3) I get an Arithmetic overflow error with all modules enabled

```
crystal /usr/share/crystal/src/array.cr:1068 array.cr
/__w/gluster-metrics-exporter/gluster-metrics-exporter/lib/glustercli/src/glustercli.cr:102 glustercli.cr
/__w/gluster-metrics-exporter/gluster-metrics-exporter/src/gluster-metrics-exporter.cr:40 gluster-metrics-exporter.cr
crystal /usr/share/crystal/src/http/server/handler.cr:30 handler.cr
/__w/gluster-metrics-exporter/gluster-metrics-exporter/lib/kemal/src/kemal/static_file_handler.cr:5 static_file_handler.cr
crystal /usr/share/crystal/src/http/server/handler.cr:30 handler.cr
crystal /usr/share/crystal/src/http/server/handler.cr:30 handler.cr
crystal /usr/share/crystal/src/http/server/handler.cr:30 handler.cr
crystal /usr/share/crystal/src/http/server/request_processor.cr:51 request_processor.cr
crystal /usr/share/crystal/src/fiber.cr:143 fiber.cr
```

glusterfs version 10.1-1ubuntu0.2 (Ubuntu 22.04)

If i turn off some modules with `--disable-all --enable=volume,peer` I don't get the error. 

I believe this to be related or similar to issue #29, so I have included my `gluster volume status all detail --xml` output as instructed in that issue:

[gluster-volume-status.xml.txt](https://github.com/user-attachments/files/15613829/gluster-volume-status.xml.txt)

Like @todeb, I'm mainly interested in the output of the `volume_status` module.

**Comment by hbro** [comment]
Like @JanSoderback, I am also running into this issue. Specifically (and only) with `volume_status` enabled.

glusterfs version 9.6 on CentOS 7.9.2009 (yes, migrating away from it)
gluster-metrics-exporter version 0.5.0

Outputs of `gluster volume status all detail --xml` and `gluster volume info --xml`:
[gluster_volume_status_all.xml.txt](https://github.com/user-attachments/files/16012173/gluster_volume_status_all.xml.txt)
[gluster_volume_info.xml.txt](https://github.com/user-attachments/files/16012175/gluster_volume_info.xml.txt)



On an unrelated note: Loading the metrics page takes 4m15s if the `peer` metrics are enabled. Might be my network taking forever, in which case a configurable timeout would be nice. Or it can be something else entirely...

**Comment by aravindavk** [comment]
I will look into the issue and update here.

**Comment by JanSoderback** [comment]
Thank you for your update, but I'm afraid I still see an Arithmetic overflow in glustercli.cr when `volume_status` module is enabled

![image](https://github.com/kadalu/gluster-metrics-exporter/assets/33482897/3c51f8a8-afcf-4fd1-bf53-d3710acd6a1a)

Updated `gluster volume status all detail output`: 
[gluster-volume-status.xml.txt](https://github.com/user-attachments/files/16057791/gluster-volume-status.xml.txt)
